package org.jboss.ddoyle.rhsummit2014.bags;

import org.jboss.ddoyle.brms.workshop.cep.model.BagScannedEvent;
import org.jboss.ddoyle.brms.workshop.cep.model.Location;

global org.jboss.ddoyle.brms.workshop.cep.command.CommandFactory commandFactory;

declare BagScannedEvent
    @role( event )
    @timestamp( timestamp.getTime() )
    @expires( 2d )
end


rule "BaggageLostAtSorting"
when
    $b1:BagScannedEvent( location == Location.CHECK_IN ) from entry-point RHSummitStream
    not BagScannedEvent( bagTag.id == $b1.bagTag.id, location == Location.SORTING, this after[0s,10m] $b1 ) from entry-point RHSummitStream
then
	channels["commandDispatchChannel"].send(commandFactory.getSystemOutCommand("Baggage lost at sorting. BagTag ID: " + $b1.getBagTag().getId(), drools));
end